[package]
name = "peach-data"
version = "0.1.0"
authors = ["James Peach <jpeach6@bloomberg.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
